# MediaMTX Configuration for dStream
logLevel: info
api: yes
apiAddress: :9990

# Timeouts
readTimeout: 30s
writeTimeout: 30s
writeQueueSize: 1024

# Auth
# authMethod: http
# authHTTPAddress: http://host.docker.internal:5655/api/auth/publish

# HLS
hls: yes
hlsAddress: :8880
hlsDirectory: /hls
hlsAlwaysRemux: yes
hlsAllowOrigins: [ "*" ]
hlsVariant: fmp4

# WebRTC
webrtc: yes
webrtcAddress: :8889
webrtcLocalUDPAddress: :8181
webrtcLocalTCPAddress: :8189
webrtcAllowOrigins: [ "*" ]
webrtcAdditionalHosts: [ "dstream.stream", "www.dstream.stream", "localhost", "127.0.0.1" ]



paths:

  # Catch-all
  all:
    source: publisher
